### ISSUE TITLE
有的时候下载失败是网络的原因吗？

### ISSUE THREAD

**Issue by 644968328** [jsycdut/mac-setup#1]

**Comment by jsycdut** [comment]
是的，下载失败和网络有关，中科大的源有时候也会出问题，比如19年有段时间就是中科大的服务器坏了，导致那段时间也下载不了文件

**Comment by jsycdut** [comment]
其实我写这个脚本也就是偷个懒，下载和网络环境关系比较密切，如果你自己能科学上网，可以使用brew官方的源，体验会更加的流畅
